version: "3.9"

services:
  # n8n service
  n8n:
    build: .
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - N8N_REDIS_HOST=redis
      - N8N_REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    restart: always

  # PostgreSQL service
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Redis service
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  # Queue worker (separate n8n worker container)
  n8n-worker:
    build: .
    container_name: n8n-worker
    command: n8n worker
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - N8N_REDIS_HOST=redis
      - N8N_REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  postgres_data:
